### ISSUE TITLE
New alarm window opens in ackward place

### ISSUE THREAD

**Issue by gsilvapt** [lapisdecor/bzoing#10]
On my end, the new alarm window is opening in the bottom right side. this is not a very comfortable place. 

Could/Should we move it to some other place like below the icon or the calendar?

**Comment by lapisdecor** [comment]
This should be easy to implement with the window.move() method. Go for it! :-)

**Comment by ghost** [comment]
Gtk.Window.move() does not work for all Window Managers as stated on the api reference. https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.move 

I'll do the fix to start every window on the center of the screen and maybe we then make a ehancement to use this behavior as a fallback from the "move" implementation.

**Comment by lapisdecor** [comment]
I'm not sure how wayland will behave but let's give it a try.
