### ISSUE TITLE
Put current time + 1 hour by default on set alarm window

### ISSUE THREAD

**Issue by lapisdecor** [lapisdecor/bzoing#16]
Currently default time on SetAlarmWindow is 0:0, but is common that a user wont want to set the time for a time before current time. Current time is also not an option since the alarm will also not be accepted. I was thinking current time +1 hour would be a good choice.

**Comment by ghost** [comment]
#18 Solved needs to be aproved

**Comment by lapisdecor** [comment]
I've just tested it and it seems to do the job. Closing the issue.
