### ISSUE TITLE
python error with the last snap

### ISSUE THREAD

**Issue by Gaara14** [lapisdecor/bzoing#28]
Hello !

Under Ubuntu 22.04, the program can't launch:
`ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

update-mime-database: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

/snap/bzoing/650/bin/desktop-launch: line 10: /snap/bzoing/650/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: No such file or directory

ERROR: update-mime-database /home/guillaume/snap/bzoing/650/.local/share/mime exited abnormally with status 127

ERROR: /snap/bzoing/650/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 127

ERROR: ld.so: object '/snap/bzoing/650/lib/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

python3: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

Only the dev version works well
`snap install --edge bzoing`

**Comment by lapisdecor** [comment]
Thanks for reporting this.
Can you please do a
`sudo snap refresh bzoing`
and report if it's now working?

**Comment by Gaara14** [comment]
All works well now.
Thanks
