### ISSUE TITLE
Alarms are not saved when computer shuts down while Bzoing is running

### ISSUE THREAD

**Issue by lapisdecor** [lapisdecor/bzoing#8]
if we shut down the computer while bzoing is running, the tasks are not beeing saved.  This may be because the monitor cycle waits for one second before it notices config.can_quit is True.

**Comment by gsilvapt** [comment]
Can confirm this issue.

I think we could have it saving the task llist in as a temporary file. When you shut down the application or the system, it can export to some other location, allowing the app to restore your task lists when it wakes up.

**Comment by lapisdecor** [comment]
Closing this one as tasks are now saved on task creation and task remove and on application quit. Since the task file is persistent but is replaced, there is actually no need to handle shutdown.
